### ISSUE TITLE
Consider LowRISC's final version

### ISSUE THREAD

**Issue by bluewww** [pulp-platform/style-guidelines#6]
This [version](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md) is basically the one we have in more detail.

**Comment by andreaskurth** [comment]
Good point. Note in particular how similar the [condensed guidelines](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#appendix---condensed-style-guide) are to "Absolute Minimum".

I think we could archive this repo and simply let the README point to the other repo.

**Comment by zarubaf** [comment]
Will do!
